name: GET UP

on:
  workflow_dispatch:
    inputs:
      message:
        description: "weather message"
        required: false

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  SUNO_COOKIE: ${{ secrets.SUNO_COOKIE }}
  OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
  SD_API_KEY: ${{ secrets.SD3_KEY }}

jobs:
  sync:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: install python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: GET RANDOM REOO
        run: |
          repos=("jbranchaud/til" "simonw/til" "thoughtbot/til") # add more repos here
          random_repo=${repos[$RANDOM % ${#repos[@]}]}
          IFS='/' read -ra parts <<< "$random_repo"
          echo "MORNING_USER_NAME=${parts[0]}" >> $GITHUB_ENV
          echo "MORNING_REPO_NAME=${parts[1]}" >> $GITHUB_ENV
          echo "MORNING_BRANCH_NAME=$(git remote show https://github.com/${parts[0]}/${parts[1]}.git | awk '/HEAD branch/ {print $NF}')" >> $GITHUB_ENV
      
      - name: GET UP
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 600
          max_attempts: 2
          retry_on: error
          command: |
            git clone https://github.com/$MORNING_USER_NAME/$MORNING_REPO_NAME.git --depth 1
            python get_up.py ${{ secrets.G_T }} ${{ github.repository }}  --weather_message ": ${{ github.event.inputs.message }}" --tele_token ${{ secrets.TG_TOKEN }} --tele_chat_id ${{ secrets.TG_CHAT_ID }}
      - name: Push New Pic
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add OUT_DIR/* knowledge.txt
          git commit -m "generated today pic" || echo "no need to commit "
          git push || echo "no file change"
